In [83]:
import numpy as np

# 1. - Representing and solving systems of linear equations using matrices
## 1.1 - System of linear equations
Here is a system of linear equations (or linear system) with three equations and three unknown variables.
$$
\begin{cases}
4x_1 - 3x_2 + x_3 = -10, \\
2x_1 + x_2 + 3x_3 = 0, \\
-x_1 + 2x_2 - 5x_3 = 17,
\end{cases}
$$


To solve this system of linear equations means to find such values of the variables x1, x2, x3 that all of its equations are simultaneously satisfied.

## 1.2 - Solving systems of linear equations using matrices.
Let's prepare to solve the linear system using `NumPy`.
__A__ will be a matrix, each row will represent one equation in the system and each column will correspond to the variable x1, x2, x3 and __b__ is a 1-D array of the free (right side) coefficients:


In [84]:
A = np.array([[4, -3, 1], [2, 1, 3], [-1, 2, -5]], dtype=float)
b = np.array([-10, 0, 17], dtype=float)
print("Matrix A: ")
print(A)
print("Matrix B: ")
print(b)

Matrix A: 
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
Matrix B: 
[-10.   0.  17.]


Check the dimensions of __A__ and __b__ using `shape()` function:


In [85]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (3, 3)
Shape of b: (3,)


Now use `np.linalg.solve(A, b)` function to find the solution of the system. The result will be saved in the 1-D array x. The elements will correspond to the values of x1, x2, x3.

In [86]:
x = np.linalg.solve(A, b)
print(f"Solution: {x}")

Solution: [ 1.  4. -2.]


Try to substitute those values of x1, x2, and x3 into the original system of equations to check its consistency.

## 1.3 - Evaluating the determinant of a matrix
Matrix __A__ corresponding to the linear system is a __square matrix__ - it has the same number of rows and columns. In the case of a square matrix it is possible to calculate it's determinant - a real number that characterizes some properties of the matrix. A linear system containing three equations with three unknown variables will have one solution if and only if the matrix A has a non-zero determinant.

Let's calculate the determinant using `np.linalg.det(A)` function:


In [87]:
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}")


Determinant of matrix A: -60.00


The value is non-zero, as expected.

# 2. - Solving system of linear equations using row reduction.
## 2.1 - Preparation for row reduction.
You can see how easy it is to use contemporary packages to solve linear equations. However, for a deeper understanding of mathematical concepts, it is important to practice some solution techniques manually. The programming approach can still help here to reduce the number of arithmetical calculations, and focus on the method itself.

Here you can practice the row reduction method for the linear system with three variables.
To apply it, first, unify matrix __A__ and __b__ into one matrix using `np.hstack()` function. Note that the shape of the originally defined array __b__ was (3,) to stack it with the (3, 3) matrix you need to transform it so that it has the same number of dimensions. You cna use `.reshape((3, 1)) function:


In [88]:
A_system = np.hstack((A, b.reshape(3, 1)))
print(A_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


## 2.2 - Functions for elementary operations
Let's review __elementary operations__, which do not change the solution set of a linear system:
* Multiply any row by a non-zero number
* Add two rows and exchange on of the original rows with the result of the addition
* Swap rows
In the case of larger systems you will need to apply elementary operations multiple times. Thus, it is convenient to define the corresponding Python functions.

In [89]:
# exchange row_num of the matrix M with it's multiple by row_num_multiple
def multiply_row(m, row_num, row_num_multiple):

    if row_num > len(m) - 1:
        raise ValueError("row_num value must not exceed the number of rows in matrix")
    if row_num_multiple == 0:
        raise ValueError("Multiple must be non-zero value")

    m_new = m.copy()
    m_new[row_num] = m_new[row_num] * row_num_multiple
    return m_new

print("Original matrix: ")
print(A_system)
print("\n Matrix after its third row is multiplied by 2: ")
print(multiply_row(A_system, 2, 2))

Original matrix: 
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

 Matrix after its third row is multiplied by 2: 
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -2.   4. -10.  34.]]


In [90]:
#multiply row_num_1 by row_multiple_1_multiple and add it to the row_num_2
def add_rows(m, row_num1, row_num2, row_num_1_multiple = 1):

    if row_num1 > len(m) - 1 or row_num2 > len(m) - 1:
         raise ValueError("row_num value must not exceed the number of rows in matrix")
    if row_num_1_multiple == 0:
        raise ValueError("Multiple must be non-zero value")

    m_new = m.copy()
    m_new[row_num2] = row_num_1_multiple * m_new[row_num1] + m_new[row_num2]
    return m_new

print("Original matrix:")
print(A_system)
print("\nMatrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:")
print(add_rows(A_system,1,2))


Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [  1.   3.  -2.  17.]]


In [91]:
#exchange row_num_1 and row_num_2 of the matrix m:
def swap_rows(m, row_num1, row_num2):
     if row_num1 > len(m) - 1 or row_num2 > len(m) - 1:
         raise ValueError("row_num value must not exceed the number of rows in matrix")

     m_new = m.copy()
     m_new[[row_num1, row_num2]] = m_new[[row_num2, row_num1]]
     return m_new

print("Original matrix:")
print(A_system)
print("\nMatrix after exchange its first and third rows:")
print(swap_rows(A_system,0,2))



Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange its first and third rows:
[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


## 2.3 - Row reduction and solution of the linear system
Now you can use the defined operations to bring the matrix into row reduced form. To do this manually, it is convenient to have 1 or -1 value in the first element of the first row. Performing calculations in Python, won't provide much benefit, but it is better for illustration purposes.


In [92]:
#swapping the first and third rows: (ref is row echelon form)
A_ref = swap_rows(A_system, 0, 2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


In [93]:
#multiplying the first row by 2 and adding it to the second row
A_ref = add_rows(A_ref, 0, 1, 2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  4.  -3.   1. -10.]]


In [94]:
#multiplying the first row by 4 and adding it to the third row
A_ref = add_rows(A_ref, 0, 2, 4)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   5. -19.  58.]]


In [95]:
#multiplying the second row by -1 and adding it to the third row
A_ref = add_rows(A_ref, 1, 2, -1)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   0. -12.  24.]]


In [96]:
#diving the third row by -12
A_ref = multiply_row(A_ref, 2, -1/12)
print(A_ref)

[[-1.  2. -5. 17.]
 [ 0.  5. -7. 34.]
 [-0. -0.  1. -2.]]


Now the second row of the matrix corresponds to the equation 5x2 - 7x3 = 34 and the first row to the equation -x + 2x2 - 5x3 = 17. Referring to the elements of the matrix, you can find the values of x2 and x1:

In [101]:
x_3 = -2
x_2 = (A_ref[1, 3] - A_ref[1, 2] * x_3) / A_ref[1, 1]
x_1 = (A_ref[0,3] - A_ref[0,2] * x_3 - A_ref[0,1] * x_2) / A_ref[0,0]
print(x_1, x_2, x_3)

1.0 4.0 -2


# 3. - System of linear equations with no solutions
Given another system of linear equations:
$$
\begin{cases}
x_1 + x_2 + x_3 = 2 \\
x_2 - 3x_3 = 1 \\
2x_1 + x_2 + 5x_3 = 0
\end{cases}
$$
Let's find the determinant of the corresponding matrix:


In [102]:
A_2 = np.array([[1,1, 1], [0, 1, -3], [2, 1, 5]], dtype=float)
b_2 = np.array([2, 1, 0], dtype=float)
d_2 = np.linalg.det(A_2)
print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


It is equal to zero, thus the system cannot have one unique solution.
It will have either infinitely many solutions or none.
The consistency of it will depend on the free coefficients (right side coefficients).

In [104]:
#x_2 = np.linalg.solve(A_2, b_2) - LinAlgError: Singular matrix

Let's perform elementary transformations to see that this particular system has no solutions:


In [106]:
A_2_system = np.hstack((A_2, b_2.reshape((3, 1))))
print(A_2_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  0.]]


In [107]:
#multiplying row 0 by -2 and add it to the row 2
A_2_ref = add_rows(A_2_system, 0, 2, -2)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -4.]]


In [108]:
#adding row 1 of the new matrix to the row 2
A_2_ref = add_rows(A_2_ref, 1, 2)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0. -3.]]


The last row will correspond to the equation 0 = -3 which has no solution.
Thus the whole linear system has no solution.

# 4. - System of linear equations with infinite number of solutions


You can bring the system to consistency by changing only the free coefficients:
$$
\begin{cases}
x_1 + x_2 + x_3 = 2 \\
x_2 - 3x_3 = 1 \\
2x_1 + x_2 + 5x_3 = 3
\end{cases}
$$
Define the new array of free coefficients:


In [110]:
b_3 = np.array([2, 1, 3])

Prepare the new matrix, corresponding to the system:


In [111]:
A_3_system = np.hstack((A_2, b_3.reshape((3,1))))
print(A_3_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  3.]]


In [133]:
#multiply row 0 of the new matrix A_3_system by -2 and add it to the row 2
A_3_ref = add_rows(A_3_system, 0, 2, -2)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -1.]]


In [134]:
#add the row 1 to the row 2
A_3_ref = add_rows(A_3_ref, 1, 2)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0.  0.]]


Thus, from the corresponding linear system:
$$
\begin{cases}
x_1 + x_2 + x_3 = 2 \\
x_2 - 3x_3 = 1 \\
0 = 0
\end{cases}
$$
you can find that x2 = 1 + 3x3, substitute it into the first equation and find x1. Thus, the solutions of the linear system are:
$$
\begin{cases}
x_1 = 1 - 4x_3 \\
x_2 = 1 + 3x_3
\end{cases}
$$
where x3 is any real number.
