In [1]:
import numpy as np

# 1. - Representing and solving systems of linear equations using matrices
## 1.1 - System of linear equations
Here is a system of linear equations (or linear system) with three equations and three unknown variables.
$$
\begin{cases}
4x_1 - 3x_2 + x_3 = -10, \\
2x_1 + x_2 + 3x_3 = 0, \\
-x_1 + 2x_2 - 5x_3 = 17,
\end{cases}
$$


To solve this system of linear equations means to find such values of the variables x1, x2, x3 that all of its equations are simultaneously satisfied.

## 1.2 - Solving systems of linear equations using matrices.
Let's prepare to solve the linear system using `NumPy`.
__A__ will be a matrix, each row will represent one equation in the system and each column will correspond to the variable x1, x2, x3 and __b__ is a 1-D array of the free (right side) coefficients:


In [2]:
A = np.array([[4, -3, 1], [2, 1, 3], [-1, 2, -5]], dtype=float)
b = np.array([-10, 0, 17], dtype=float)
print("Matrix A: ")
print(A)
print("Matrix B: ")
print(b)

Matrix A: 
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
Matrix B: 
[-10.   0.  17.]


Check the dimensions of __A__ and __b__ using `shape()` function:


In [3]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (3, 3)
Shape of b: (3,)


Now use `np.linalg.solve(A, b)` function to find the solution of the system. The result will be saved in the 1-D array x. The elements will correspond to the values of x1, x2, x3.

In [4]:
x = np.linalg.solve(A, b)
print(f"Solution: {x}")

Solution: [ 1.  4. -2.]


Try to substitute those values of x1, x2, and x3 into the original system of equations to check its consistency.

## 1.3 - Evaluating the determinant of a matrix
Matrix __A__ corresponding to the linear system is a __square matrix__ - it has the same number of rows and columns. In the case of a square matrix it is possible to calculate it's determinant - a real number that characterizes some properties of the matrix. A linear system containing three equations with three unknown variables will have one solution if and only if the matrix A has a non-zero determinant.

Let's calculate the determinant using `np.linalg.det(A)` function:


In [5]:
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}")


Determinant of matrix A: -60.00


The value is non-zero, as expected.

# 2. - Solving system of linear equations using row reduction.
## 2.1 - Preparation for row reduction.
You can see how easy it is to use contemporary packages to solve linear equations. However, for a deeper understanding of mathematical concepts, it is important to practice some solution techniques manually. The programming approach can still help here to reduce the number of arithmetical calculations, and focus on the method itself.

Here you can practice the row reduction method for the linear system with three variables.
To apply it, first, unify matrix __A__ and __b__ into one matrix using `np.hstack()` function. Note that the shape of the originally defined array __b__ was (3,) to stack it with the (3, 3) matrix you need to transform it so that it has the same number of dimensions. You cna use `.reshape((3, 1)) function:


In [6]:
A_system = np.hstack((A, b.reshape(3, 1)))
print(A_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]
