## About Jupyter Notebooks
Jupyter Notebooks are interactive coding journals that integrate live code, explanatory text, equations, visualisations and other multimedia resources.



In [4]:
test = "Hello, world!"
print(test)

Hello, world!


# 1 - Basics of NumPy
Numpy is the main package for scientific computing in Python. It performs a wide variety of advanced mathematical operations with high efficiency.


In [3]:
import numpy as np

## 1.1 Advantages of using NumPy arrays.
Arrays are one of the core data structures in the NumPy library and are essential for organizing data. You can think of them as grids of values,
all of the same type. In contrast, Python lists are more limited in functionality and require more space and time to process than NumPy arrays.

NumPy provides an array object that is much faster and more compact than Python lists. Through its extensive API integration, the library offers many built-in functions that make computing much easier with only few lines of code.
This can be a huge advantage when performing math operations on large datasets.

The array object in NumPy is called `ndarray` meaning 'n-dimensional array'.
A 1-D array represents a standard list of values entirely in one dimension.
In NumPy, all of the elements within the array are of the same type.






In [ ]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

## 1.2 How to create NumPy arrays

There are several ways to create an array in NumPy. You can create a 1-D array by simply the function `array()` which takes a list of values as an argument and returns 1-D array.



In [6]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Another way to implement an array is using `np.arange()`. This function will return an array of evenly spaced values within a given interval.


In [7]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [8]:
# Create an array that from the integer 1, ends at 20, incremented by 3.
# Create value with a specific step size, but stop value is not included.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


Another way to create an array with a specific number of evenly spaced elements from the start value to the stop value is by using `np.linspace()`.

In [9]:
# Create an array that includes 5 elements spaced evenly from the integer 1 to integer 100.
# Create a specific number of values between start and stop, stop value is included by default.
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


The default type for values in the NumPy function `np.linspace` is a floating point (`np.float64`). You can easily specify your data type using `dtype`.
In addition to float, NumPy has several other data types such as `int`, and `char`.

To change the type to integers, you need to set the dtype to int.

In [10]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [11]:
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [12]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [13]:
char_arr = np.array(["Welcome to Math for ML!"])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML!']
<U23


## 1.3 More on NumPy arrays
One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as:
* `np.ones()` - returns a new array setting values to one.
* `np.zeros()` - returns a new array setting values to zero.
* `np.empty()` - returns a new uninitialized array.
* `np.random.rand()` - returns a new array with values chosen at random.

In [15]:
# Return a new array of shape 3, filled with ones.
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [16]:
# Return a new array of shape 3, filled with zeros.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [17]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [18]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.95590368 0.17484062 0.61133475]
