## About Jupyter Notebooks
Jupyter Notebooks are interactive coding journals that integrate live code, explanatory text, equations, visualisations and other multimedia resources.



In [108]:
test = "Hello, world!"
print(test)

Hello, world!


# 1 - Basics of NumPy
Numpy is the main package for scientific computing in Python. It performs a wide variety of advanced mathematical operations with high efficiency.


In [109]:
import numpy as np

## 1.1 Advantages of using NumPy arrays.
Arrays are one of the core data structures in the NumPy library and are essential for organizing data. You can think of them as grids of values,
all of the same type. In contrast, Python lists are more limited in functionality and require more space and time to process than NumPy arrays.

NumPy provides an array object that is much faster and more compact than Python lists. Through its extensive API integration, the library offers many built-in functions that make computing much easier with only few lines of code.
This can be a huge advantage when performing math operations on large datasets.

The array object in NumPy is called `ndarray` meaning 'n-dimensional array'.
A 1-D array represents a standard list of values entirely in one dimension.
In NumPy, all of the elements within the array are of the same type.






In [110]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


## 1.2 How to create NumPy arrays

There are several ways to create an array in NumPy. You can create a 1-D array by simply the function `array()` which takes a list of values as an argument and returns 1-D array.



In [111]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [112]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [113]:
# Create an array that from the integer 1, ends at 20, incremented by 3.
# Create value with a specific step size, but stop value is not included.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


Another way to create an array with a specific number of evenly spaced elements from the start value to the stop value is by using `np.linspace()`.

In [114]:
# Create an array that includes 5 elements spaced evenly from the integer 1 to integer 100.
# Create a specific number of values between start and stop, stop value is included by default.
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


The default type for values in the NumPy function `np.linspace` is a floating point (`np.float64`). You can easily specify your data type using `dtype`.
In addition to float, NumPy has several other data types such as `int`, and `char`.

To change the type to integers, you need to set the dtype to int.

In [115]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [116]:
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [117]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [118]:
char_arr = np.array(["Welcome to Math for ML!"])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML!']
<U23


## 1.3 More on NumPy arrays
One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as:
* `np.ones()` - returns a new array setting values to one.
* `np.zeros()` - returns a new array setting values to zero.
* `np.empty()` - returns a new uninitialized array.
* `np.random.rand()` - returns a new array with values chosen at random.

In [119]:
# Return a new array of shape 3, filled with ones.
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [120]:
# Return a new array of shape 3, filled with zeros.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [121]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [122]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.79381619 0.1798954  0.64399808]


# 2. Multidimensional arrays
With NumPy you can also create arrays with more than one dimension.
A multidimensional array has more than one column.


In [123]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1, 2, 3], [4, 5 ,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


An alternative way to create a multidimensional array is by reshaping the initial 1-D array. Using `np.reshape()` you can rearrange elements of the previous array into a new shape.

In [124]:
# 1-D array
one_dim_arr = np.array([1,2,3,4,5,6])
# Multidimensional array using reshape()
multi_dim_arr = np.reshape(one_dim_arr, #the array to be reshaped
                           (1, 6)) #dimensions of the new array
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3 4 5 6]]


## 2.1 - Finding size, shape and dimension.
In future assignments, you will need to know how to find the size, dimension and shape of an array.
These are all attributes of a `ndarray` and can be accessed as follows:
* `ndarray.ndim` - stores the number dimensions of the array.
* `ndarray.shape` - stores the shape of the array. each number in the tuple denotes the length of each corresponding dimension.
* `ndarray.size` - stores the number of elements in the array.



In [125]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [126]:
# Shape of the 2-D array multi_dim_arr
multi_dim_arr.shape

(1, 6)

In [127]:
# Size of the array multi_dim_arr
multi_dim_arr.size

6

# 3. Array math operations
NumPy allows to quickly perform element-wise addition, subtraction, multiplication and division for both 1-D and multidimensional arrays.
The operations are performed using the math symbol for each '+', '-', and '*'.


In [128]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays element-wise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


## 3.1 - Broadcasting
Broadcasting is a way of performing operations on arrays of different shapes by automatically expanding one or both arrays without copying data.

NumPy automatically "stretches" the smaller array along the mismatched dimensions so that element-wise operations can be done without loops.

### 3.1.1 How broadcasting works in NumPy?
Broadcasting applies specific rules to determine whether two arrays can be aligned for operations:
1. Check Dimensions: Ensure the arrays have the same number of dimensions or expandable dimensions.
2. Dimensions Padding: If arrays have different numbers of dimensions, the smaller array is left-padded with ones.
3. Shape Compatibility: Two dimensions are compatible of:
    * They are equal, or
    * One of them is 1

If every dimension satisfies one of those rules, broadcasting works.



In [129]:
# Broadcasting array in single value and 1-D addition
arr = np.array([1, 2, 3])
arr + 1 # Adds one to each element

array([2, 3, 4])

In [130]:
# Broadcasting array in 1-D and 2-D addition
a1 = np.array([2, 4, 6])
a2 = np.array([[1,3,5], [7, 9, 11]])
a1 + a2

array([[ 3,  7, 11],
       [ 9, 13, 17]])

In [131]:
# Using broadcasting for matrix multiplication
matrix = np.reshape([1,2,3,4], (2, 2))
vector = np.array([10, 20])
matrix * vector

array([[10, 40],
       [30, 80]])

In [132]:
# Using broadcasting for multiplying vector with a scalar
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

In [133]:
# For any axis length 1, use the only possible value.)
x = np.array(([0, 1, 2], [3, 4, 5], [6, 7 ,8]))
y = np.array([1, 10, 100]).reshape(3, 1)

print(x+y)

#x (3, 3)
#y (3, 1)

shape = (3, 3)
out = np.empty(shape, dtype=int)
N0, N1 = shape

for i in range(N0):
    for j in range(N1):
        out[i, j] = x[i, j] + y[i, 0]
print(out)

[[  1   2   3]
 [ 13  14  15]
 [106 107 108]]
[[  1   2   3]
 [ 13  14  15]
 [106 107 108]]


In [134]:
# Omit variables for prepended 1's
x = np.array([[[0,1,2],[3,4,5],[6,7,8]],
              [[9,10, 11],[12, 13, 14],[15,16,17]]]) #shape (2, 3, 3)
y = np.array([1, 10, 100]) #shape (3,)

print(x+y)

#x (2, 3, 3)
#y (1, 1, 3)

shape = (2, 3, 3)
out = np.empty(shape, dtype=int)
N0, N1, N2 = shape

for i in range(N0):
    for j in range(N1):
        for k in range(N2):
            out[i, j, k] = x[i, j, k] + y[k]

print(out)

[[[  1  11 102]
  [  4  14 105]
  [  7  17 108]]

 [[ 10  20 111]
  [ 13  23 114]
  [ 16  26 117]]]
[[[  1  11 102]
  [  4  14 105]
  [  7  17 108]]

 [[ 10  20 111]
  [ 13  23 114]
  [ 16  26 117]]]


In [135]:
# Both arrays can have broadcasted axes, not just one.
x = np.array([[0], [1], [2]]) #(3, 1)
y = np.array([[3, 4, 5]]) #(1, 3)

print(x + y)

shape = (3, 3)
out = np.empty(shape, dtype=int)

N0, N1 = shape

for i in range(N0):
    for j in range(N1):
        out[i,j] = x[i, 0] + y[0, j]
print(out)

[[3 4 5]
 [4 5 6]
 [5 6 7]]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


# 4. Indexing and slicing
Indexing is very useful as it allows you to select specific elements from an array.

## 4.1 Indexing
Lets us select specific elements from the arrays as given.



In [136]:
# Select the third element of the array.
a = np.array([1, 2 ,3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


For multidimensional arrays of shape `n`, to index a specific element, you must input `n` indices, one for each dimension.

In [137]:
# Indexing on a 2-D array
two_dim = np.array(([1,2,3], [4, 5, 6], [7,8,9]))
# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])
print(two_dim[2, 1])

8
8


## 4.2 Slicing
Slicing gives you a sublist of elements that you specify from the array.

The syntax is:
`array[start:end:step]`




In [138]:
# Slice the array a to get the [2, 3, 4]
a[1:4]

array([2, 3, 4])

In [139]:
# Slice the array a to get the [1, 2, 3]
a[:3]

array([1, 2, 3])

In [140]:
# Slice the array a to get the [3, 4, 5]
a[2:]

array([3, 4, 5])

In [141]:
# Slice the array a to get the [1, 3, 5]
a[::2]

array([1, 3, 5])

In [142]:
# Slice the 2-D array to get the first two rows
two_dim[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
# Slice the 2-D array to get the last two rows
two_dim[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [144]:
# Slice the 2-D array to get the second column.
two_dim[:, 1]

array([2, 5, 8])

## 5. Stacking
Stacking is a feature of NumPy that leads to increased customization of arrays.
It means to join two or more arrays, either horizontally or vertically, meaning that it is done along new axis.
* `np.vstack()` - stacks vertically
* `np.hstack()` - stacks horizontally


In [145]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

vert_stack = np.vstack((a1, a2))
print("Vertical stack: \n", vert_stack)

horz_stack = np.hstack((a1, a2))
print("Horizontal stack: \n", horz_stack)

axis0_stack = np.stack((a1, a2), axis=0)
print("Axis0: \n", axis0_stack)

axis1_stack = np.stack((a1, a2), axis=1)
print("Axis1: \n",axis1_stack)

axis2_stack = np.stack((a1, a2), axis=2)
print("Axis2: \n",axis2_stack)

Vertical stack: 
 [[1 1]
 [2 2]
 [3 3]
 [4 4]]
Horizontal stack: 
 [[1 1 3 3]
 [2 2 4 4]]
Axis0: 
 [[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]
Axis1: 
 [[[1 1]
  [3 3]]

 [[2 2]
  [4 4]]]
Axis2: 
 [[[1 3]
  [1 3]]

 [[2 4]
  [2 4]]]


### Axes
Axes are directions along NumPy array. Any value in array can be identified by its position along the axes.

In [146]:
array = np.arange(1, 13).reshape(3, 4)
print(array)
print(array[1, 2]) # axis-0 (rows) - 1, axis-1 (columns) - 2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7


# 6. Basic data analysis operations
## 6.1 Summation



In [147]:
one_dim = np.array([1, 2, 3, 4, 5])
two_dim = np.array([[1,2,3], [4,5,6]])

print(np.sum(one_dim)) # Sum of all elements
print(np.sum(two_dim)) # Sum of all elements

print(np.sum(two_dim, axis=0)) # Sum along axis 0 (column-wise)
print(np.sum(two_dim, axis=1)) # Sum along axis 1 (row-wise)

total_saved_dim = np.sum(two_dim, axis=1, keepdims=True) # The number of dimensions is preserved
print(total_saved_dim)
print(total_saved_dim.shape)

print(np.cumsum(one_dim))
print(np.cumsum(two_dim))

15
21
[5 7 9]
[ 6 15]
[[ 6]
 [15]]
(2, 1)
[ 1  3  6 10 15]
[ 1  3  6 10 15 21]


## 6.2 Maximum and minimum


In [148]:
print(one_dim.min())
print(one_dim.max())

print(two_dim.max())
print(two_dim.min())

1
5
6
1


## 7. Joining and splitting
## 7.1 Joining/concatenation


In [149]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6,7,8,9,10])

print(np.concatenate((a1, a2))) # Concatenating/join two arrays together

a3 = np.array([[1, 2, 3], [4, 5, 6]])
a4 = np.array([[7,8,9], [10, 11, 12]])

print(np.concatenate((a3, a4), axis=0))
print(np.vstack((a3, a4)))

print(np.concatenate((a3, a4), axis=1))
print(np.hstack((a3, a4)))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## 7.2 Splitting

In [150]:
arr = np.array([1, 2, 3 ,4, 5,6 ])
print(np.array_split(arr, 3)) # Splitting 1-D array
print(np.array_split(arr, 4)) # Will adjust from the end accordingly

arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(np.array_split(arr1, 3))

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(np.array_split(arr2, 3))
print(np.array_split(arr2, 3, axis=1))

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
